<?php

/**
 * Do not edit this file manually, generated by the Yeoman Phalcon generator
 * Register application modules for the ComparisonAPI project
 */
return [
	'backend' => [
		'className' => '\App\Modules\Backend\Module',
		'path' => __DIR__ . '/../Modules/Backend/Module.php',
	],

	'frontend' => [
		'className' => '\App\Modules\Frontend\Module',
		'path' => __DIR__ . '/../Modules/Frontend/Module.php',
	],

	'leads' => [
		'className' => '\App\Modules\Leads\Module',
		'path' => __DIR__ . '/../Modules/Leads/Module.php',
	],

	'admin' => [
		'className' => '\App\Modules\Admin\Module',
		'path' => __DIR__ . '/../Modules/Admin/Module.php',
	],

	'oauth' => [
		'className' => '\App\Modules\Oauth\Module',
		'path' => __DIR__ . '/../Modules/Oauth/Module.php',
	],
];





